version: '3.8'

services:
  bot-app:
    environment:
      - DEBUG=1
    build:
      target: dev
    volumes:
      - ./app/src:/usr/src
    ports:
      - 5678:5678

  bot-ib:
    ports:
      - 5000:5000
